version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.epoptes.debian
    environment:
      - DISPLAY=host.docker.internal:0
      - DEBUG=
    networks:
      - epoptes
  epoptes-client-1:
    build:
      context: .
      dockerfile: Dockerfile.epoptes-client.debian
    environment:
      - DISPLAY=host.docker.internal:0
      - DEBUG=
    networks:
      - epoptes
    hostname: epoptes-client-1
    depends_on:
      - server

networks:
  epoptes:
